from __future__ import annotations
from typing import Protocol, List
from .header import PackedData

class BitPacking(Protocol):
    def compress(self, arr: List[int]) -> PackedData: ...
    def decompress(self, out: List[int], data: PackedData) -> None: ...
    def get(self, i: int, data: PackedData) -> int: ...
